<script setup lang="ts">
import { mdiAccountOutline, mdiBellOutline, mdiChevronDown, mdiEyeOutline, mdiLockOutline, mdiLogoutVariant, mdiPaletteOutline, mdiShieldOutline, mdiTranslate, mdiTrophyOutline } from '@mdi/js'

const tab = ref<'personal' | 'settings'>('personal')
const form = reactive({ name: 'Имя Фамилия', email: 'email.dfghj2@gmail.com', phone: '+7 (456) 1239 45 56', birthdate: '15.05.2025', city: 'Алматы' })
const notifications = reactive({ email: true, push: true, sms: false })
const lang = ref('ru')
const theme = ref('light')
</script>

<template>
  <div class="profile-page"><div class="profile-layout"><aside class="profile-sidebar"><div class="profile-user-card"><div class="profile-avatar"><MdiIcon :path="mdiAccountOutline" :size="52" /></div><h2 class="profile-user-name">Имя Фамилия</h2><span class="profile-user-badge">Взрослый аккаунт</span><div class="profile-user-divider" /><div class="profile-user-meta"><div v-for="[key,value] in [['Город','Алматы'],['UserID','id3456'],['Регистрация','20.05.2026']]" :key="key" class="profile-meta-row"><span class="profile-meta-key">{{ key }}</span><span class="profile-meta-val">{{ value }}</span></div></div><button class="profile-logout" @click="navigateTo('/login')"><MdiIcon :path="mdiLogoutVariant" :size="20" />Выйти с аккаунта</button></div></aside>
    <div class="profile-main"><div class="profile-card"><div class="profile-tabs"><button class="profile-tab" :class="{ 'profile-tab--active': tab === 'personal' }" @click="tab = 'personal'">Личные данные</button><button class="profile-tab" :class="{ 'profile-tab--active': tab === 'settings' }" @click="tab = 'settings'">Настройки</button></div>
      <div v-if="tab === 'personal'" class="profile-tab-content"><div class="profile-form-grid"><div v-for="field in [{k:'name',l:'ФИО',t:'text'},{k:'email',l:'Почта',t:'email'},{k:'phone',l:'Телефон',t:'tel'},{k:'birthdate',l:'Дата рождения',t:'text'}]" :key="field.k" class="profile-field"><label class="profile-label">{{ field.l }}</label><input v-model="form[field.k as keyof typeof form]" class="profile-input" :type="field.t"></div><div class="profile-field profile-field--full"><label class="profile-label">Город проживания</label><div class="profile-select-wrap"><select v-model="form.city" class="profile-input profile-select"><option>Алматы</option><option>Астана</option><option>Шымкент</option><option>Караганда</option></select><MdiIcon :path="mdiChevronDown" :size="20" class="profile-select-icon" /></div></div></div><div class="profile-actions"><button class="profile-btn profile-btn--primary">Сохранить данные</button><button class="profile-btn profile-btn--ghost">Отмена</button></div></div>
      <div v-else class="profile-tab-content"><div class="profile-settings-group"><h3 class="profile-settings-title"><MdiIcon :path="mdiBellOutline" :size="20" />Уведомления</h3><div class="profile-settings-divider" /><div v-for="[key,label] in [['email','Email-уведомления'],['push','Push-уведомления'],['sms','СМС-информирование']]" :key="key" class="profile-settings-row"><span>{{ label }}</span><button role="switch" class="profile-toggle" :class="{ 'profile-toggle--on': notifications[key as keyof typeof notifications] }" @click="notifications[key as keyof typeof notifications] = !notifications[key as keyof typeof notifications]"><span class="profile-toggle__thumb" /></button></div></div><div class="profile-settings-group"><h3 class="profile-settings-title"><MdiIcon :path="mdiLockOutline" :size="20" />Безопасность</h3><div class="profile-settings-divider" /><div class="profile-security-btns"><button class="profile-btn profile-btn--outline"><MdiIcon :path="mdiEyeOutline" :size="20" />Изменить пароль</button><button class="profile-btn profile-btn--outline"><MdiIcon :path="mdiShieldOutline" :size="20" />Настроить двухфакторную аутентификацию</button></div></div><div class="profile-settings-bottom"><div class="profile-settings-group profile-settings-group--half"><h3 class="profile-settings-title"><MdiIcon :path="mdiTranslate" :size="20" />Язык интерфейса</h3><select v-model="lang" class="profile-input"><option value="ru">Русский</option><option value="kz">Қазақша</option></select></div><div class="profile-settings-group profile-settings-group--half"><h3 class="profile-settings-title"><MdiIcon :path="mdiPaletteOutline" :size="20" />Тема оформления</h3><div class="profile-settings-divider" /><div class="profile-theme-options" role="radiogroup" aria-label="Тема оформления"><label v-for="item in ['light','dark','system']" :key="item" class="profile-radio"><input v-model="theme" class="profile-radio__input" type="radio" name="profile-theme" :value="item"><span class="profile-radio__circle" :class="{ 'profile-radio__circle--checked': theme === item }" aria-hidden="true"><span v-if="theme === item" class="profile-radio__dot" /></span><span class="profile-radio__label">{{ item === 'light' ? 'Светлая' : item === 'dark' ? 'Тёмная' : 'Системная' }}</span></label></div></div></div></div>
    </div><div class="profile-card profile-achievements"><div class="profile-achievements-header"><h3 class="profile-achievements-title">Ваши достижения</h3><NuxtLink to="/education" class="profile-achievements-link">Смотреть курсы</NuxtLink></div><div class="profile-achievements-empty"><MdiIcon :path="mdiTrophyOutline" :size="48" /><p>Здесь будут отображаться достижения после прохождения курсов и тестов.</p></div></div></div></div></div>
</template>
