# Generated by Django 5.2.16 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('official_url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
